Assemble migration message
UKHomeOffice/hocs-cms-data-migrator pull request #42
Opened 2022-08-04 10:29 UTC by rjweeks

### HOCS-5386

Build a test migration message and validate it is valid according to the migration schema.

2022-08-04 10:40 UTC, SWhitlam requested changes
added a few comments to consider. The main issue is I think we should be using the central CI scripts which should already have the right config in them.

2022-08-04 10:40 UTC, SWhitlam commented on build.gradle
> +	afterTest { desc, result ->
do you need this?

2022-08-04 10:40 UTC, SWhitlam commented on config/1-setup-sqs.sh
> +#!/bin/bash
I don't think you need these files anymore now that you're using the main CI scripts? The config is now setup here https://github.com/UKHomeOffice/hocs-ci-infrastructure/blob/227cfe52a07ba3e1bb7802fdb83dcac8318f324c/localstack

2022-08-04 10:40 UTC, SWhitlam commented on docker-compose.yml
> +version: '3.8'
This is now configured in the central CI pipeline repo here https://github.com/UKHomeOffice/hocs-ci-infrastructure/blob/227cfe52a07ba3e1bb7802fdb83dcac8318f324c/docker-compose.yml#L405

2022-08-04 10:40 UTC, SWhitlam commented on src/main/java/uk/gov/digital/ho/hocs/cms/document/CaseDetails.java
> +public class CaseDetails {
You could use @Builder here instead of using Setters?

2022-08-04 10:40 UTC, SWhitlam commented on src/test/java/uk/gov/digital/ho/hocs/cms/document/CaseMigrationMessageTest.java
> +        try {
Why not throw these exceptions rather than using try catch?

2022-08-04 10:40 UTC, SWhitlam commented on src/test/java/uk/gov/digital/ho/hocs/cms/document/CaseMigrationMessageTest.java
> +        InputStream schemaStream = inputStreamFromClasspath("hocs-migration-schema.json");
could you use the Spring  `ClassPathResource("hocs-migration-schema.json")` here instead?

2022-08-05 10:08 UTC, rjweeks commented on build.gradle
> +	afterTest { desc, result ->
Removed.

2022-08-05 10:08 UTC, rjweeks commented on config/1-setup-sqs.sh
> +#!/bin/bash
Removed.

2022-08-05 10:08 UTC, rjweeks commented on docker-compose.yml
> +version: '3.8'
Removed.

2022-08-05 10:37 UTC, rjweeks commented on src/test/java/uk/gov/digital/ho/hocs/cms/document/CaseMigrationMessageTest.java
> +        try {
Done.

2022-08-05 12:25 UTC, rjweeks commented on src/main/java/uk/gov/digital/ho/hocs/cms/document/CaseDetails.java
> +public class CaseDetails {
Done

2022-08-05 12:34 UTC, rjweeks commented on src/test/java/uk/gov/digital/ho/hocs/cms/document/CaseMigrationMessageTest.java
> +        InputStream schemaStream = inputStreamFromClasspath("hocs-migration-schema.json");
Done

2022-08-08 09:23 UTC, SWhitlam approved these changes

2022-08-08 11:25 UTC, merged